/* Kult — catalogue de démonstration
 * id, t: titre, k: type (film|serie|livre), y: année, g: genres,
 * c: créateur·rice (réalisateur / showrunner / auteur), r: note /10,
 * d: description, m: méta (durée / saisons / pages), h: teinte de l'affiche (0-360)
 */
const CATALOG = [
  // ─── Films ───
  { id: "f01", t: "Inception", k: "film", y: 2010, g: ["Science-fiction", "Thriller", "Action"], c: "Christopher Nolan", r: 8.8, d: "Un voleur infiltre les rêves pour implanter une idée dans l'esprit d'un héritier.", m: "2h28", h: 220 },
  { id: "f02", t: "Interstellar", k: "film", y: 2014, g: ["Science-fiction", "Drame", "Aventure"], c: "Christopher Nolan", r: 8.7, d: "Des explorateurs traversent un trou de ver pour sauver l'humanité d'une Terre mourante.", m: "2h49", h: 205 },
  { id: "f03", t: "Le Voyage de Chihiro", k: "film", y: 2001, g: ["Animation", "Fantasy", "Aventure"], c: "Hayao Miyazaki", r: 8.6, d: "Une fillette égarée dans un monde d'esprits doit travailler pour libérer ses parents.", m: "2h05", h: 350 },
  { id: "f04", t: "Parasite", k: "film", y: 2019, g: ["Thriller", "Drame", "Comédie"], c: "Bong Joon-ho", r: 8.5, d: "Une famille pauvre s'immisce au service d'une famille riche, jusqu'au basculement.", m: "2h12", h: 150 },
  { id: "f05", t: "La La Land", k: "film", y: 2016, g: ["Romance", "Drame", "Feel-good"], c: "Damien Chazelle", r: 8.0, d: "À Los Angeles, une actrice et un pianiste de jazz poursuivent leurs rêves en musique.", m: "2h08", h: 265 },
  { id: "f06", t: "Le Fabuleux Destin d'Amélie Poulain", k: "film", y: 2001, g: ["Comédie", "Romance", "Feel-good"], c: "Jean-Pierre Jeunet", r: 8.3, d: "Une serveuse de Montmartre décide en secret de réparer la vie des autres.", m: "2h02", h: 130 },
  { id: "f07", t: "Intouchables", k: "film", y: 2011, g: ["Comédie", "Drame", "Feel-good"], c: "Toledano & Nakache", r: 8.5, d: "L'amitié improbable entre un aristocrate tétraplégique et son aide à domicile de banlieue.", m: "1h52", h: 30 },
  { id: "f08", t: "Dune : Deuxième partie", k: "film", y: 2024, g: ["Science-fiction", "Aventure", "Action"], c: "Denis Villeneuve", r: 8.6, d: "Paul Atreides s'unit aux Fremen pour venger sa famille et affronter son destin.", m: "2h46", h: 35 },
  { id: "f09", t: "Blade Runner 2049", k: "film", y: 2017, g: ["Science-fiction", "Thriller", "Mystère"], c: "Denis Villeneuve", r: 8.0, d: "Un blade runner découvre un secret enfoui qui pourrait faire basculer la société.", m: "2h44", h: 25 },
  { id: "f10", t: "La Communauté de l'Anneau", k: "film", y: 2001, g: ["Fantasy", "Aventure", "Action"], c: "Peter Jackson", r: 8.9, d: "Un hobbit hérite d'un anneau maléfique qu'il doit détruire au cœur du Mordor.", m: "2h58", h: 110 },
  { id: "f11", t: "Matrix", k: "film", y: 1999, g: ["Science-fiction", "Action", "Dystopie"], c: "Les Wachowski", r: 8.7, d: "Un hacker découvre que la réalité est une simulation contrôlée par les machines.", m: "2h16", h: 140 },
  { id: "f12", t: "Pulp Fiction", k: "film", y: 1994, g: ["Crime", "Drame", "Comédie"], c: "Quentin Tarantino", r: 8.9, d: "Destins croisés de gangsters, d'un boxeur et de deux braqueurs à Los Angeles.", m: "2h34", h: 45 },
  { id: "f13", t: "Le Parrain", k: "film", y: 1972, g: ["Crime", "Drame", "Classique"], c: "Francis Ford Coppola", r: 9.2, d: "Le patriarche d'une dynastie mafieuse transmet son empire à son fils réticent.", m: "2h55", h: 0 },
  { id: "f14", t: "Forrest Gump", k: "film", y: 1994, g: ["Drame", "Romance", "Feel-good"], c: "Robert Zemeckis", r: 8.8, d: "Un homme simple traverse quarante ans d'histoire américaine avec candeur.", m: "2h22", h: 200 },
  { id: "f15", t: "Fight Club", k: "film", y: 1999, g: ["Drame", "Thriller"], c: "David Fincher", r: 8.8, d: "Un insomniaque et un vendeur de savon fondent un club de combat clandestin.", m: "2h19", h: 340 },
  { id: "f16", t: "Gladiator", k: "film", y: 2000, g: ["Action", "Drame", "Historique"], c: "Ridley Scott", r: 8.5, d: "Un général romain trahi devient gladiateur pour venger sa famille.", m: "2h35", h: 40 },
  { id: "f17", t: "Whiplash", k: "film", y: 2014, g: ["Drame"], c: "Damien Chazelle", r: 8.5, d: "Un jeune batteur de jazz se brûle sous la férule d'un professeur tyrannique.", m: "1h47", h: 50 },
  { id: "f18", t: "The Grand Budapest Hotel", k: "film", y: 2014, g: ["Comédie", "Aventure", "Mystère"], c: "Wes Anderson", r: 8.1, d: "Un concierge légendaire et son lobby boy sont mêlés au vol d'un tableau inestimable.", m: "1h39", h: 320 },
  { id: "f19", t: "Your Name", k: "film", y: 2016, g: ["Animation", "Romance", "Fantasy"], c: "Makoto Shinkai", r: 8.4, d: "Deux adolescents échangent mystérieusement leurs corps à distance.", m: "1h46", h: 250 },
  { id: "f20", t: "Coco", k: "film", y: 2017, g: ["Animation", "Aventure", "Feel-good"], c: "Lee Unkrich", r: 8.4, d: "Un jeune musicien voyage au pays des morts pour percer un secret de famille.", m: "1h45", h: 15 },
  { id: "f21", t: "Oppenheimer", k: "film", y: 2023, g: ["Drame", "Historique", "Biographie"], c: "Christopher Nolan", r: 8.3, d: "L'ascension et la chute du père de la bombe atomique.", m: "3h00", h: 28 },
  { id: "f22", t: "Everything Everywhere All at Once", k: "film", y: 2022, g: ["Science-fiction", "Comédie", "Action"], c: "Les Daniels", r: 7.8, d: "Une gérante de laverie découvre qu'elle doit sauver le multivers.", m: "2h19", h: 290 },
  { id: "f23", t: "Le Silence des agneaux", k: "film", y: 1991, g: ["Thriller", "Crime", "Horreur"], c: "Jonathan Demme", r: 8.6, d: "Une jeune agente du FBI consulte un psychiatre cannibale pour traquer un tueur.", m: "1h58", h: 80 },
  { id: "f24", t: "Seven", k: "film", y: 1995, g: ["Thriller", "Crime", "Mystère"], c: "David Fincher", r: 8.6, d: "Deux inspecteurs traquent un tueur en série inspiré des sept péchés capitaux.", m: "2h07", h: 60 },
  { id: "f25", t: "Shutter Island", k: "film", y: 2010, g: ["Thriller", "Mystère", "Drame"], c: "Martin Scorsese", r: 8.2, d: "Un marshal enquête sur une disparition dans un asile psychiatrique insulaire.", m: "2h18", h: 190 },
  { id: "f26", t: "La Ligne verte", k: "film", y: 1999, g: ["Drame", "Fantastique", "Crime"], c: "Frank Darabont", r: 8.6, d: "Dans le couloir de la mort, un colosse condamné possède un don miraculeux.", m: "3h09", h: 120 },
  { id: "f27", t: "Les Évadés", k: "film", y: 1994, g: ["Drame", "Crime", "Classique"], c: "Frank Darabont", r: 9.3, d: "Condamné à tort, un banquier tisse vingt ans d'amitié et d'espoir en prison.", m: "2h22", h: 210 },
  { id: "f28", t: "Retour vers le futur", k: "film", y: 1985, g: ["Science-fiction", "Comédie", "Aventure"], c: "Robert Zemeckis", r: 8.5, d: "Un lycéen voyage en 1955 et manque d'empêcher la rencontre de ses parents.", m: "1h56", h: 185 },
  { id: "f29", t: "Alien, le huitième passager", k: "film", y: 1979, g: ["Horreur", "Science-fiction", "Classique"], c: "Ridley Scott", r: 8.5, d: "L'équipage d'un cargo spatial est traqué par une créature implacable.", m: "1h57", h: 160 },
  { id: "f30", t: "Get Out", k: "film", y: 2017, g: ["Horreur", "Thriller", "Mystère"], c: "Jordan Peele", r: 7.8, d: "Un week-end chez les parents de sa compagne vire au cauchemar insidieux.", m: "1h44", h: 355 },
  { id: "f31", t: "Mad Max : Fury Road", k: "film", y: 2015, g: ["Action", "Science-fiction", "Dystopie"], c: "George Miller", r: 8.1, d: "Une poursuite furieuse à travers un désert post-apocalyptique.", m: "2h00", h: 20 },
  { id: "f32", t: "Portrait de la jeune fille en feu", k: "film", y: 2019, g: ["Romance", "Drame", "Historique"], c: "Céline Sciamma", r: 8.1, d: "Au XVIIIᵉ siècle, une peintre tombe amoureuse de celle qu'elle doit portraiturer.", m: "2h02", h: 165 },
  { id: "f33", t: "La Haine", k: "film", y: 1995, g: ["Drame", "Crime", "Classique"], c: "Mathieu Kassovitz", r: 8.1, d: "Vingt-quatre heures dans la vie de trois amis de banlieue après une bavure policière.", m: "1h38", h: 230 },
  { id: "f34", t: "Astérix & Obélix : Mission Cléopâtre", k: "film", y: 2002, g: ["Comédie", "Aventure", "Feel-good"], c: "Alain Chabat", r: 7.6, d: "Numérobis doit bâtir un palais en trois mois, potion magique à la rescousse.", m: "1h47", h: 48 },
  { id: "f35", t: "Princesse Mononoké", k: "film", y: 1997, g: ["Animation", "Fantasy", "Aventure"], c: "Hayao Miyazaki", r: 8.4, d: "Un prince maudit se retrouve au cœur de la guerre entre forêt et industrie.", m: "2h14", h: 100 },
  { id: "f36", t: "Un Prophète", k: "film", y: 2009, g: ["Crime", "Drame"], c: "Jacques Audiard", r: 7.8, d: "Un jeune détenu gravit les échelons du crime derrière les barreaux.", m: "2h35", h: 75 },
  { id: "f37", t: "Titanic", k: "film", y: 1997, g: ["Romance", "Drame", "Historique"], c: "James Cameron", r: 7.9, d: "Une romance impossible à bord du paquebot le plus célèbre de l'histoire.", m: "3h14", h: 215 },
  { id: "f38", t: "Le Roi Lion", k: "film", y: 1994, g: ["Animation", "Aventure", "Jeunesse"], c: "Allers & Minkoff", r: 8.5, d: "Un lionceau exilé doit reconquérir son royaume et son destin.", m: "1h28", h: 38 },

  // ─── Séries ───
  { id: "s01", t: "Breaking Bad", k: "serie", y: 2008, g: ["Crime", "Drame", "Thriller"], c: "Vince Gilligan", r: 9.5, d: "Un prof de chimie condamné se mue en baron de la méthamphétamine.", m: "5 saisons", h: 90 },
  { id: "s02", t: "Stranger Things", k: "serie", y: 2016, g: ["Science-fiction", "Horreur", "Aventure"], c: "Les frères Duffer", r: 8.6, d: "Des ados des années 80 affrontent un monde parallèle terrifiant.", m: "5 saisons", h: 0 },
  { id: "s03", t: "Game of Thrones", k: "serie", y: 2011, g: ["Fantasy", "Drame", "Action"], c: "Benioff & Weiss", r: 9.2, d: "Des maisons nobles s'entredéchirent pour le Trône de fer.", m: "8 saisons", h: 210 },
  { id: "s04", t: "The Office", k: "serie", y: 2005, g: ["Comédie", "Feel-good"], c: "Greg Daniels", r: 9.0, d: "Le quotidien absurde d'un bureau de papeterie filmé en faux documentaire.", m: "9 saisons", h: 55 },
  { id: "s05", t: "Friends", k: "serie", y: 1994, g: ["Comédie", "Romance", "Feel-good"], c: "Crane & Kauffman", r: 8.9, d: "Six amis new-yorkais entre colocs, cafés et histoires de cœur.", m: "10 saisons", h: 270 },
  { id: "s06", t: "The Crown", k: "serie", y: 2016, g: ["Drame", "Historique", "Biographie"], c: "Peter Morgan", r: 8.6, d: "Les coulisses du règne d'Élisabeth II, des années 40 à nos jours.", m: "6 saisons", h: 225 },
  { id: "s07", t: "Dark", k: "serie", y: 2017, g: ["Science-fiction", "Mystère", "Thriller"], c: "Baran bo Odar", r: 8.7, d: "Des disparitions d'enfants révèlent un vertigineux nœud temporel entre quatre familles.", m: "3 saisons", h: 195 },
  { id: "s08", t: "La Casa de Papel", k: "serie", y: 2017, g: ["Crime", "Thriller", "Action"], c: "Álex Pina", r: 8.2, d: "Huit braqueurs et un cerveau orchestrent le casse du siècle à la Fabrique de la monnaie.", m: "5 parties", h: 358 },
  { id: "s09", t: "Lupin", k: "serie", y: 2021, g: ["Crime", "Mystère", "Action"], c: "George Kay", r: 7.5, d: "Un gentleman cambrioleur inspiré d'Arsène Lupin venge son père.", m: "3 parties", h: 45 },
  { id: "s10", t: "Le Bureau des Légendes", k: "serie", y: 2015, g: ["Thriller", "Drame"], c: "Éric Rochant", r: 8.7, d: "Le quotidien sous tension des agents clandestins de la DGSE.", m: "5 saisons", h: 205 },
  { id: "s11", t: "Dix pour cent", k: "serie", y: 2015, g: ["Comédie", "Drame", "Feel-good"], c: "Fanny Herrero", r: 8.2, d: "Une agence d'artistes parisienne jongle avec les caprices des stars.", m: "4 saisons", h: 310 },
  { id: "s12", t: "The Last of Us", k: "serie", y: 2023, g: ["Drame", "Horreur", "Aventure"], c: "Mazin & Druckmann", r: 8.7, d: "Un contrebandier escorte une adolescente à travers une Amérique ravagée.", m: "2 saisons", h: 95 },
  { id: "s13", t: "Chernobyl", k: "serie", y: 2019, g: ["Drame", "Historique", "Thriller"], c: "Craig Mazin", r: 9.3, d: "Minute par minute, la catastrophe nucléaire et le mensonge d'État.", m: "Mini-série", h: 85 },
  { id: "s14", t: "Black Mirror", k: "serie", y: 2011, g: ["Science-fiction", "Dystopie", "Thriller"], c: "Charlie Brooker", r: 8.7, d: "Anthologie grinçante sur nos relations toxiques à la technologie.", m: "7 saisons", h: 175 },
  { id: "s15", t: "Peaky Blinders", k: "serie", y: 2013, g: ["Crime", "Drame", "Historique"], c: "Steven Knight", r: 8.8, d: "L'ascension d'un clan de gangsters à Birmingham après la Grande Guerre.", m: "6 saisons", h: 218 },
  { id: "s16", t: "Sherlock", k: "serie", y: 2010, g: ["Mystère", "Crime", "Drame"], c: "Moffat & Gatiss", r: 9.0, d: "Le détective légendaire transposé dans le Londres du XXIᵉ siècle.", m: "4 saisons", h: 240 },
  { id: "s17", t: "True Detective", k: "serie", y: 2014, g: ["Crime", "Mystère", "Thriller"], c: "Nic Pizzolatto", r: 8.9, d: "Deux inspecteurs hantés par une affaire rituelle en Louisiane.", m: "4 saisons", h: 65 },
  { id: "s18", t: "Fleabag", k: "serie", y: 2016, g: ["Comédie", "Drame", "Romance"], c: "Phoebe Waller-Bridge", r: 8.7, d: "Une Londonienne caustique brise le quatrième mur pour raconter ses failles.", m: "2 saisons", h: 335 },
  { id: "s19", t: "The Bear", k: "serie", y: 2022, g: ["Drame", "Comédie"], c: "Christopher Storer", r: 8.5, d: "Un chef étoilé reprend la sandwicherie familiale de Chicago, en apnée.", m: "4 saisons", h: 32 },
  { id: "s20", t: "Succession", k: "serie", y: 2018, g: ["Drame", "Comédie"], c: "Jesse Armstrong", r: 8.9, d: "Les héritiers d'un magnat des médias se déchirent pour sa succession.", m: "4 saisons", h: 222 },
  { id: "s21", t: "Severance", k: "serie", y: 2022, g: ["Science-fiction", "Mystère", "Thriller"], c: "Dan Erickson", r: 8.7, d: "Des employés ont séparé chirurgicalement leurs souvenirs de bureau et de vie privée.", m: "2 saisons", h: 180 },
  { id: "s22", t: "Arcane", k: "serie", y: 2021, g: ["Animation", "Action", "Fantasy"], c: "Linke & Yee", r: 9.0, d: "Deux sœurs que tout oppose dans une cité déchirée entre magie et technologie.", m: "2 saisons", h: 285 },
  { id: "s23", t: "L'Attaque des Titans", k: "serie", y: 2013, g: ["Animation", "Action", "Fantasy"], c: "Hajime Isayama", r: 9.1, d: "L'humanité retranchée derrière des murs lutte contre des titans dévoreurs.", m: "4 saisons", h: 105 },
  { id: "s24", t: "Better Call Saul", k: "serie", y: 2015, g: ["Crime", "Drame"], c: "Gilligan & Gould", r: 9.0, d: "La lente métamorphose d'un petit avocat en Saul Goodman.", m: "6 saisons", h: 42 },
  { id: "s25", t: "Mindhunter", k: "serie", y: 2017, g: ["Crime", "Thriller", "Drame"], c: "Joe Penhall", r: 8.6, d: "Deux agents du FBI inventent le profilage en interrogeant des tueurs en série.", m: "2 saisons", h: 200 },
  { id: "s26", t: "Fargo", k: "serie", y: 2014, g: ["Crime", "Drame", "Comédie"], c: "Noah Hawley", r: 8.9, d: "Anthologie de crimes absurdes et sanglants dans le Midwest enneigé.", m: "5 saisons", h: 190 },
  { id: "s27", t: "Westworld", k: "serie", y: 2016, g: ["Science-fiction", "Dystopie", "Mystère"], c: "Nolan & Joy", r: 8.5, d: "Dans un parc d'attractions peuplé d'androïdes, les hôtes s'éveillent.", m: "4 saisons", h: 15 },
  { id: "s28", t: "The Mandalorian", k: "serie", y: 2019, g: ["Science-fiction", "Aventure", "Action"], c: "Jon Favreau", r: 8.6, d: "Un chasseur de primes solitaire protège un mystérieux enfant.", m: "3 saisons", h: 155 },
  { id: "s29", t: "Downton Abbey", k: "serie", y: 2010, g: ["Drame", "Historique", "Romance"], c: "Julian Fellowes", r: 8.7, d: "Aristocrates et domestiques dans un manoir anglais au début du XXᵉ siècle.", m: "6 saisons", h: 145 },
  { id: "s30", t: "Normal People", k: "serie", y: 2020, g: ["Romance", "Drame"], c: "Abrahamson & Macdonald", r: 8.4, d: "L'histoire d'amour intermittente de deux jeunes Irlandais, du lycée à l'université.", m: "Mini-série", h: 118 },
  { id: "s31", t: "Squid Game", k: "serie", y: 2021, g: ["Thriller", "Drame", "Dystopie"], c: "Hwang Dong-hyeok", r: 8.0, d: "Des endettés s'affrontent dans des jeux d'enfants mortels pour une fortune.", m: "3 saisons", h: 330 },
  { id: "s32", t: "The Wire", k: "serie", y: 2002, g: ["Crime", "Drame", "Classique"], c: "David Simon", r: 9.3, d: "Baltimore disséquée : rue, police, docks, politique, école et presse.", m: "5 saisons", h: 208 },

  // ─── Livres ───
  { id: "l01", t: "1984", k: "livre", y: 1949, g: ["Dystopie", "Science-fiction", "Classique"], c: "George Orwell", r: 9.0, d: "Sous l'œil de Big Brother, Winston ose penser par lui-même.", m: "368 pages", h: 355 },
  { id: "l02", t: "Le Petit Prince", k: "livre", y: 1943, g: ["Jeunesse", "Philosophie", "Classique"], c: "Antoine de Saint-Exupéry", r: 8.7, d: "Un aviateur échoué rencontre un petit prince venu d'une autre planète.", m: "96 pages", h: 45 },
  { id: "l03", t: "Harry Potter à l'école des sorciers", k: "livre", y: 1997, g: ["Fantasy", "Jeunesse", "Aventure"], c: "J.K. Rowling", r: 8.9, d: "Un orphelin découvre qu'il est sorcier et entre à Poudlard.", m: "320 pages", h: 275 },
  { id: "l04", t: "L'Étranger", k: "livre", y: 1942, g: ["Classique", "Philosophie", "Drame"], c: "Albert Camus", r: 8.5, d: "Meursault, indifférent au monde, commet un meurtre sous le soleil d'Alger.", m: "184 pages", h: 50 },
  { id: "l05", t: "Dune", k: "livre", y: 1965, g: ["Science-fiction", "Aventure", "Classique"], c: "Frank Herbert", r: 8.8, d: "Sur la planète des sables, Paul Atreides devient l'élu d'un peuple.", m: "704 pages", h: 33 },
  { id: "l06", t: "Le Seigneur des anneaux", k: "livre", y: 1954, g: ["Fantasy", "Aventure", "Classique"], c: "J.R.R. Tolkien", r: 9.1, d: "L'épopée fondatrice de la fantasy moderne autour d'un anneau unique.", m: "1 216 pages", h: 112 },
  { id: "l07", t: "Cent ans de solitude", k: "livre", y: 1967, g: ["Classique", "Fantastique", "Drame"], c: "Gabriel García Márquez", r: 8.7, d: "La saga envoûtante de la famille Buendía à Macondo.", m: "448 pages", h: 60 },
  { id: "l08", t: "Crime et Châtiment", k: "livre", y: 1866, g: ["Classique", "Crime", "Philosophie"], c: "Fiodor Dostoïevski", r: 8.9, d: "Un étudiant assassine une usurière et sombre dans le tourment moral.", m: "672 pages", h: 15 },
  { id: "l09", t: "Orgueil et Préjugés", k: "livre", y: 1813, g: ["Romance", "Classique", "Comédie"], c: "Jane Austen", r: 8.8, d: "Elizabeth Bennet et Mr Darcy, le duel d'esprit le plus célèbre de la littérature.", m: "480 pages", h: 300 },
  { id: "l10", t: "Le Comte de Monte-Cristo", k: "livre", y: 1844, g: ["Aventure", "Classique", "Drame"], c: "Alexandre Dumas", r: 9.0, d: "Trahi et emprisonné, Edmond Dantès orchestre une vengeance magistrale.", m: "1 312 pages", h: 195 },
  { id: "l11", t: "Les Misérables", k: "livre", y: 1862, g: ["Classique", "Drame", "Historique"], c: "Victor Hugo", r: 8.9, d: "Jean Valjean, forçat en quête de rédemption dans la France du XIXᵉ.", m: "1 664 pages", h: 230 },
  { id: "l12", t: "La Peste", k: "livre", y: 1947, g: ["Classique", "Philosophie", "Drame"], c: "Albert Camus", r: 8.4, d: "Oran en quarantaine : chronique de la solidarité face à l'absurde.", m: "288 pages", h: 70 },
  { id: "l13", t: "Sapiens", k: "livre", y: 2011, g: ["Historique", "Philosophie", "Biographie"], c: "Yuval Noah Harari", r: 8.3, d: "Une brève histoire de l'humanité, de la savane aux algorithmes.", m: "512 pages", h: 165 },
  { id: "l14", t: "L'Alchimiste", k: "livre", y: 1988, g: ["Philosophie", "Aventure", "Feel-good"], c: "Paulo Coelho", r: 7.9, d: "Un berger andalou part chercher un trésor et se trouve lui-même.", m: "224 pages", h: 42 },
  { id: "l15", t: "Da Vinci Code", k: "livre", y: 2003, g: ["Thriller", "Mystère", "Aventure"], c: "Dan Brown", r: 7.5, d: "Un symbologue déchiffre une conspiration millénaire cachée dans l'art.", m: "576 pages", h: 260 },
  { id: "l16", t: "Millénium : Les hommes qui n'aimaient pas les femmes", k: "livre", y: 2005, g: ["Thriller", "Crime", "Mystère"], c: "Stieg Larsson", r: 8.2, d: "Un journaliste et une hackeuse géniale rouvrent une disparition vieille de 40 ans.", m: "576 pages", h: 350 },
  { id: "l17", t: "La Vérité sur l'affaire Harry Quebert", k: "livre", y: 2012, g: ["Thriller", "Mystère", "Romance"], c: "Joël Dicker", r: 8.0, d: "Un écrivain enquête sur son mentor accusé d'un meurtre vieux de 33 ans.", m: "672 pages", h: 185 },
  { id: "l18", t: "Au revoir là-haut", k: "livre", y: 2013, g: ["Historique", "Drame", "Crime"], c: "Pierre Lemaitre", r: 8.3, d: "Deux rescapés des tranchées montent une arnaque monumentale.", m: "624 pages", h: 25 },
  { id: "l19", t: "La Nuit des temps", k: "livre", y: 1968, g: ["Science-fiction", "Romance", "Classique"], c: "René Barjavel", r: 8.4, d: "Sous l'Antarctique, une civilisation endormie depuis 900 000 ans.", m: "416 pages", h: 178 },
  { id: "l20", t: "Fondation", k: "livre", y: 1951, g: ["Science-fiction", "Classique"], c: "Isaac Asimov", r: 8.6, d: "Un mathématicien prédit la chute de l'Empire galactique et prépare l'après.", m: "416 pages", h: 245 },
  { id: "l21", t: "Le Meilleur des mondes", k: "livre", y: 1932, g: ["Dystopie", "Science-fiction", "Classique"], c: "Aldous Huxley", r: 8.5, d: "Une société du bonheur obligatoire, conditionnée dès l'éprouvette.", m: "320 pages", h: 150 },
  { id: "l22", t: "Fahrenheit 451", k: "livre", y: 1953, g: ["Dystopie", "Science-fiction", "Classique"], c: "Ray Bradbury", r: 8.3, d: "Dans un monde où les livres brûlent, un pompier se met à lire.", m: "224 pages", h: 20 },
  { id: "l23", t: "Kafka sur le rivage", k: "livre", y: 2002, g: ["Fantastique", "Drame", "Mystère"], c: "Haruki Murakami", r: 8.2, d: "Un adolescent fugueur et un vieil homme qui parle aux chats, destins liés.", m: "640 pages", h: 130 },
  { id: "l24", t: "L'Ombre du vent", k: "livre", y: 2001, g: ["Mystère", "Drame", "Romance"], c: "Carlos Ruiz Zafón", r: 8.5, d: "Dans la Barcelone d'après-guerre, un livre maudit entraîne Daniel dans un labyrinthe.", m: "576 pages", h: 55 },
  { id: "l25", t: "Le Nom de la rose", k: "livre", y: 1980, g: ["Mystère", "Historique", "Crime"], c: "Umberto Eco", r: 8.4, d: "Des moines meurent dans une abbaye ; Guillaume de Baskerville enquête.", m: "640 pages", h: 90 },
  { id: "l26", t: "Shining", k: "livre", y: 1977, g: ["Horreur", "Thriller", "Fantastique"], c: "Stephen King", r: 8.3, d: "Gardien d'un hôtel isolé, Jack Torrance sombre sous son emprise maléfique.", m: "576 pages", h: 5 },
  { id: "l27", t: "L'Anomalie", k: "livre", y: 2020, g: ["Science-fiction", "Thriller", "Philosophie"], c: "Hervé Le Tellier", r: 7.9, d: "Un vol Paris–New York atterrit deux fois, avec les mêmes passagers.", m: "336 pages", h: 200 },
  { id: "l28", t: "Changer l'eau des fleurs", k: "livre", y: 2018, g: ["Drame", "Romance", "Feel-good"], c: "Valérie Perrin", r: 8.4, d: "Une garde-cimetière au grand cœur voit sa vie bousculée par un mystère.", m: "560 pages", h: 315 },
  { id: "l29", t: "La Passe-miroir : Les Fiancés de l'hiver", k: "livre", y: 2013, g: ["Fantasy", "Aventure", "Romance"], c: "Christelle Dabos", r: 8.5, d: "Ophélie, liseuse d'objets, est fiancée de force sur une arche glaciale.", m: "528 pages", h: 190 },
  { id: "l30", t: "Le Problème à trois corps", k: "livre", y: 2008, g: ["Science-fiction", "Mystère", "Thriller"], c: "Liu Cixin", r: 8.1, d: "Un premier contact extraterrestre aux conséquences vertigineuses.", m: "512 pages", h: 170 },
  { id: "l31", t: "Nos étoiles contraires", k: "livre", y: 2012, g: ["Romance", "Drame", "Jeunesse"], c: "John Green", r: 7.8, d: "Deux adolescents atteints de cancer s'aiment avec un humour féroce.", m: "336 pages", h: 210 },
  { id: "l32", t: "Le Trône de fer", k: "livre", y: 1996, g: ["Fantasy", "Aventure", "Drame"], c: "George R.R. Martin", r: 8.8, d: "Le roman-fleuve d'intrigues et de trahisons qui a inspiré la série culte.", m: "800 pages", h: 218 },
];

const GENRES = [...new Set(CATALOG.flatMap((x) => x.g))].sort((a, b) => a.localeCompare(b, "fr"));

const KIND_LABEL = { film: "Film", serie: "Série", livre: "Livre" };
const KIND_PLURAL = { film: "Films", serie: "Séries", livre: "Livres" };
const KIND_DONE_VERB = { film: "Vu", serie: "Vue", livre: "Lu" };
